# Generated by Django 5.1.3 on 2024-11-22 06:04

import myT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myT', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=myT.models.user_profile_image_path),
        ),
    ]
