# Generated by Django 5.1.3 on 2024-11-19 08:44

import myT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myT', '0002_remove_plan_content_post_comment_postimage_heart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=myT.models.post_image_upload_to),
        ),
    ]
