# Generated by Django 5.1.3 on 2024-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myT', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_reply',
            field=models.IntegerField(default=False),
        ),
    ]
