# Generated by Django 5.1.3 on 2024-11-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myT', '0003_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plandetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
