# Generated by Django 5.1.3 on 2024-11-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myT', '0004_plandetail_latitude_plandetail_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
