# Generated by Django 5.1.3 on 2024-11-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myT', '0006_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
